cust1 = Customer.new("Isaac", "Fiore")
cust2 = Customer.new("Barack", "Obama")
cust3 = Customer.new("Monkey", "Luffy")
cust4 = Customer.new("Naruto", "Uzumaki")
cust5 = Customer.new("Slug", "Christ")
cust6 = Customer.new("Lil", "Uzi")
cust7 = Customer.new("Big", "Wet")
cust8 = Customer.new("Yas", "Queen")
cust9 = Customer.new("Rick", "Owens")
cust10 = Customer.new("Isaac", "Bird")

restaurant1 = Restaurant.new("Autre Kyo Ya")
restaurant2 = Restaurant.new("Continental Bar")
restaurant3 = Restaurant.new("Poco")
restaurant4 = Restaurant.new("14th and 1st Loosie Spot")
restaurant5 = Restaurant.new("Ya Mom's House")

cust1.add_review(restaurant1, "Its Lit")
cust2.add_review(restaurant2, "Its Ok")
cust3.add_review(restaurant3, "Its Dece")
cust4.add_review(restaurant4, "Its Awesome")
cust5.add_review(restaurant5, "Its Lit")
cust6.add_review(restaurant2, "Im Lit")
cust7.add_review(restaurant4, "Its Loud")
cust8.add_review(restaurant3, "Its Dark")
cust9.add_review(restaurant3, "Its Quiet")
cust10.add_review(restaurant1, "Its Overpriced")
